version: '3'
services:
  app:
    build:
      context: ..  # Go up one directory to use the main project as context
      dockerfile: docker/Dockerfile  # Path to Dockerfile in the docker directory
    ports:
      - "8000:8000"  # Map port 8000 on your local machine to port 8000 in the container
    volumes:
      - ../app:/app  # Volume for real-time code syncing
    image: myapp  # Name the image 'myapp'
